// Files to cache
const cacheName = 'js13kPWA-v1';
const appShellFiles = [
'/',
'/index.html',
'/404.html',
'/app.js',
'/js13kpwa.webmanifest',
'/sitemap.xml',
'/sitemap.xml.gz',
'/Abgasentsorgung/index.html',
'/Anhang/index.html',
'/assets/images/favicon.png',
'/assets/javascripts/bundle.6c7ad80a.min.js',
'/assets/javascripts/bundle.6c7ad80a.min.js.map',
'/assets/javascripts/lunr/tinyseg.js',
'/assets/javascripts/lunr/wordcut.js',
'/assets/javascripts/lunr/min/lunr.ar.min.js',
'/assets/javascripts/lunr/min/lunr.da.min.js',
'/assets/javascripts/lunr/min/lunr.de.min.js',
'/assets/javascripts/lunr/min/lunr.du.min.js',
'/assets/javascripts/lunr/min/lunr.es.min.js',
'/assets/javascripts/lunr/min/lunr.fi.min.js',
'/assets/javascripts/lunr/min/lunr.fr.min.js',
'/assets/javascripts/lunr/min/lunr.hi.min.js',
'/assets/javascripts/lunr/min/lunr.hu.min.js',
'/assets/javascripts/lunr/min/lunr.it.min.js',
'/assets/javascripts/lunr/min/lunr.ja.min.js',
'/assets/javascripts/lunr/min/lunr.jp.min.js',
'/assets/javascripts/lunr/min/lunr.multi.min.js',
'/assets/javascripts/lunr/min/lunr.nl.min.js',
'/assets/javascripts/lunr/min/lunr.no.min.js',
'/assets/javascripts/lunr/min/lunr.pt.min.js',
'/assets/javascripts/lunr/min/lunr.ro.min.js',
'/assets/javascripts/lunr/min/lunr.ru.min.js',
'/assets/javascripts/lunr/min/lunr.stemmer.support.min.js',
'/assets/javascripts/lunr/min/lunr.sv.min.js',
'/assets/javascripts/lunr/min/lunr.th.min.js',
'/assets/javascripts/lunr/min/lunr.tr.min.js',
'/assets/javascripts/lunr/min/lunr.vi.min.js',
'/assets/javascripts/lunr/min/lunr.zh.min.js',
'/assets/javascripts/workers/search.b97dbffb.min.js',
'/assets/javascripts/workers/search.b97dbffb.min.js.map',
'/assets/stylesheets/main.1d29e8d0.min.css',
'/assets/stylesheets/main.1d29e8d0.min.css.map',
'/assets/stylesheets/palette.cbb835fc.min.css',
'/assets/stylesheets/palette.cbb835fc.min.css.map',
'/Betrieb/index.html',
'/Blockheizkraftwerk BHKW/index.html',
'/docs/BHKW_Betriebsdatenbuch.pdf',
'/docs/Emissionen_Zūndbox_Abgassystem.pdf',
'/docs/Jenbacher_TA 1000-0300_Gasqualität.pdf',
'/docs/PCA P2032 Overview_NOxMASTER™_BlueJetG1_V1.pdf',
'/docs/PCA P2032_SCR Manual_DE.cleaned.pdf',
'/docs/Technisches_Schema_Jenbacher.jpg',
'/Eigenbedarfsversorgung/index.html',
'/Gaskessel/index.html',
'/Gasversorgung/index.html',
'/icons/icon-128.png',
'/icons/icon-192.png',
'/icons/icon-256.png',
'/icons/icon-32.png',
'/icons/icon-512.png',
'/icons/icon-64.png',
'/Infrastrukturanlagen/index.html',
'/media/favicon.png',
'/media/image1.jpg',
'/media/image10.jpg',
'/media/image11.jpg',
'/media/image12.jpg',
'/media/image13.jpg',
'/media/image14.jpg',
'/media/image15.jpeg',
'/media/image16.jpg',
'/media/image17.jpg',
'/media/image18.jpg',
'/media/image19.jpg',
'/media/image2.png',
'/media/image20.jpg',
'/media/image21.jpg',
'/media/image22.jpg',
'/media/image23.jpg',
'/media/image24.jpg',
'/media/image25.jpg',
'/media/image26.jpg',
'/media/image27.jpg',
'/media/image28.jpg',
'/media/image29.jpg',
'/media/image3.png',
'/media/image30.jpg',
'/media/image31.jpg',
'/media/image32.jpg',
'/media/image33.jpg',
'/media/image34.jpg',
'/media/image35.jpg',
'/media/image36.jpg',
'/media/image37.jpg',
'/media/image38.jpg',
'/media/image39.jpg',
'/media/image4.png',
'/media/image40.jpg',
'/media/image41.jpg',
'/media/image42.jpg',
'/media/image43.jpg',
'/media/image44.jpg',
'/media/image45.jpg',
'/media/image46.jpg',
'/media/image47.jpg',
'/media/image48.jpg',
'/media/image49.jpg',
'/media/image5.png',
'/media/image50.jpg',
'/media/image51.jpg',
'/media/image52.jpg',
'/media/image53.jpg',
'/media/image54.jpg',
'/media/image55.jpg',
'/media/image56.jpg',
'/media/image57.jpg',
'/media/image58.jpg',
'/media/image59.jpg',
'/media/image6.png',
'/media/image60.jpg',
'/media/image61.jpg',
'/media/image62.jpg',
'/media/image63.jpg',
'/media/image64.jpg',
'/media/image65.jpg',
'/media/image66.jpg',
'/media/image67.jpg',
'/media/image68.jpg',
'/media/image69.jpg',
'/media/image7.png',
'/media/image70.jpg',
'/media/image71.jpg',
'/media/image72.jpg',
'/media/image73.jpg',
'/media/image74.jpg',
'/media/image75.jpg',
'/media/image76.jpg',
'/media/image77.jpg',
'/media/image78.jpg',
'/media/image79.jpg',
'/media/image8.png',
'/media/image80.jpg',
'/media/image81.jpg',
'/media/image82.jpg',
'/media/image83.jpg',
'/media/image84.jpg',
'/media/image85.jpg',
'/media/image86.jpg',
'/media/image87.jpg',
'/media/image88.jpg',
'/media/image89.jpg',
'/media/image9.png',
'/media/image90.jpg',
'/media/image91.jpg',
'/media/image92.jpg',
'/media/image93.jpg',
'/media/image94.jpg',
'/media/image95.jpg',
'/media/image96.jpg',
'/media/logo.png',
'/search/search_index.json',
'/Sicherheit/index.html',
'/stylesheets/caution.css',
'/stylesheets/danger.css',
'/stylesheets/styles.css',
'/stylesheets/tables.css',
'/stylesheets/warning.css',
'/Wasserkreisläufe/index.html',
'/Zu dieser Dokumentation/index.html',
'/Übersicht/index.html'
];

// Installing Service Worker
self.addEventListener('install', (e) => {
  console.log('[Service Worker] Install');
  e.waitUntil((async () => {
    const cache = await caches.open(cacheName);
    console.log('[Service Worker] Caching all: app shell and content');
    await cache.addAll(appShellFiles);
  })());
});

// Fetching content using Service Worker
self.addEventListener('fetch', (e) => {
  e.respondWith((async () => {
    const r = await caches.match(e.request);
    console.log(`[Service Worker] Fetching resource: ${e.request.url}`);
    if (r) return r;
    const response = await fetch(e.request);
    const cache = await caches.open(cacheName);
    console.log(`[Service Worker] Caching new resource: ${e.request.url}`);
    cache.put(e.request, response.clone());
    return response;
  })());
});
